basePath: /api
definitions:
  models.AuthenticationResponse:
    properties:
      token:
        type: string
      userId:
        type: string
      username:
        type: string
    type: object
  models.Credentials:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  models.PersonalDataResponse:
    properties:
      age:
        type: integer
      email:
        type: string
      gender:
        type: string
      image:
        type: string
      lastName:
        type: string
      name:
        type: string
      username:
        type: string
    type: object
host: localhost:5000
info:
  contact:
    email: luispalominot@hotmail.com
    name: Luis Palomino
  description: This is the API documentation for GuessIt
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: GuessIt API
  version: "0.1"
paths:
  /User/Login:
    post:
      consumes:
      - application/json
      description: login user to system
      operationId: user-login
      parameters:
      - description: User credentials
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.Credentials'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Bad:
              description: OK
              type: string
          schema:
            $ref: '#/definitions/models.AuthenticationResponse'
            type: object
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Login
  /User/PersonalData:
    get:
      description: Retrieve personal data from user
      operationId: personal-data-retrieval
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PersonalDataResponse'
            type: object
        "401":
          description: Unauthorized
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - Bearer: []
      summary: PersonalData
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
