version: '3'
services:
  redis:
    image: 'redis'
    container_name: "guessit-redis"
    ports:
      - "6379:6379"
  mongodb:
    image: 'mongo'
    container_name: "guessit-mongo"
    ports:
      - "27017:27017"
  golang:
    env_file:
      - .env
    build: '.'
    container_name: "guessit-backend"
    links:
      - mongodb
      - redis
    volumes:
      - .:/src
      - ./static:/static
    ports:
      - "5000:5000"
  